console.log('Hello World, semantic-release')
console.log('Use semantic-release build version')
console.log('try build next release')
console.log('run auto-changelog update changelog')
console.log('auto-changelog use temp')